package com.arcos;

import java.io.BufferedReader;
import java.io.FileReader;
import java.nio.charset.StandardCharsets;
import java.util.LinkedHashMap;
import java.util.Map;

/**
 * Checks the packet codec against frames generated by ARIA itself.
 *
 * <p>{@code tools/golden_vectors.cpp} links the real AriaCoda library and dumps
 * what {@code ArRobotPacketSender} puts on the wire for a spread of commands,
 * including the awkward ones: negative arguments, which travel as a magnitude
 * under a different type tag, and VEL2, whose two wheel bytes get narrowed to a
 * signed short on the way out.
 *
 * <p>Runs on a desktop JVM — nothing in {@code com.arcos} core touches Android.
 */
public final class ProtocolTest {

    private static int checks;
    private static int failures;

    public static void main(String[] args) throws Exception {
        String vectors = args.length > 0 ? args[0] : "tools/golden_vectors.txt";
        testAgainstAria(vectors);
        testRoundTrip();
        testChecksumRejection();
        testFramerResync();
        testSipDecode();

        System.out.println();
        if (failures == 0) {
            System.out.println("PASS - " + checks + " checks");
        } else {
            System.out.println("FAIL - " + failures + " of " + checks + " checks failed");
            System.exit(1);
        }
    }

    // ---------- against ARIA's own output ----------

    private static void testAgainstAria(String path) throws Exception {
        System.out.println("== golden vectors from AriaCoda (" + path + ")");
        Map<String, String> golden = new LinkedHashMap<>();
        try (BufferedReader r = new BufferedReader(new FileReader(path))) {
            String line;
            while ((line = r.readLine()) != null) {
                line = line.trim();
                if (line.isEmpty()) {
                    continue;
                }
                int sp = line.indexOf(' ');
                golden.put(line.substring(0, sp), line.substring(sp + 1));
            }
        }

        Map<String, ArcosPacket> mine = new LinkedHashMap<>();
        mine.put("SYNC0", ArcosPacket.command(Arcos.SYNC_0));
        mine.put("SYNC1", ArcosPacket.command(Arcos.SYNC_1));
        mine.put("SYNC2", ArcosPacket.command(Arcos.SYNC_2));
        mine.put("PULSE", ArcosPacket.command(Arcos.PULSE));
        mine.put("ESTOP", ArcosPacket.command(Arcos.ESTOP));

        mine.put("OPEN_1", ArcosPacket.commandInt(Arcos.OPEN, 1));
        mine.put("CLOSE_1", ArcosPacket.commandInt(Arcos.CLOSE, 1));
        mine.put("ENABLE_1", ArcosPacket.commandInt(Arcos.ENABLE, 1));
        mine.put("ENABLE_0", ArcosPacket.commandInt(Arcos.ENABLE, 0));
        mine.put("SONAR_1", ArcosPacket.commandInt(Arcos.SONAR, 1));
        mine.put("SONAR_0", ArcosPacket.commandInt(Arcos.SONAR, 0));
        mine.put("SETO_0", ArcosPacket.commandInt(Arcos.SETO, 0));
        mine.put("STOP_1", ArcosPacket.commandInt(Arcos.STOP, 1));
        mine.put("HOSTBAUD_2", ArcosPacket.commandInt(Arcos.HOSTBAUD, Arcos.baudCode(38400)));

        mine.put("VEL_0", ArcosPacket.commandInt(Arcos.VEL, 0));
        mine.put("VEL_300", ArcosPacket.commandInt(Arcos.VEL, 300));
        mine.put("VEL_NEG300", ArcosPacket.commandInt(Arcos.VEL, -300));
        mine.put("VEL_1", ArcosPacket.commandInt(Arcos.VEL, 1));
        mine.put("VEL_NEG1", ArcosPacket.commandInt(Arcos.VEL, -1));
        mine.put("VEL_255", ArcosPacket.commandInt(Arcos.VEL, 255));
        mine.put("VEL_256", ArcosPacket.commandInt(Arcos.VEL, 256));
        mine.put("VEL_32767", ArcosPacket.commandInt(Arcos.VEL, 32767));
        mine.put("VEL_NEG32767", ArcosPacket.commandInt(Arcos.VEL, -32767));

        mine.put("RVEL_45", ArcosPacket.commandInt(Arcos.RVEL, 45));
        mine.put("RVEL_NEG45", ArcosPacket.commandInt(Arcos.RVEL, -45));
        mine.put("SETV_500", ArcosPacket.commandInt(Arcos.SETV, 500));
        mine.put("SETRV_100", ArcosPacket.commandInt(Arcos.SETRV, 100));
        mine.put("SETA_300", ArcosPacket.commandInt(Arcos.SETA, 300));
        mine.put("SETA_NEG300", ArcosPacket.commandInt(Arcos.SETA, -300));
        mine.put("SETRA_100", ArcosPacket.commandInt(Arcos.SETRA, 100));
        mine.put("MOVE_1000", ArcosPacket.commandInt(Arcos.MOVE, 1000));
        mine.put("MOVE_NEG1000", ArcosPacket.commandInt(Arcos.MOVE, -1000));
        mine.put("HEAD_90", ArcosPacket.commandInt(Arcos.HEAD, 90));
        mine.put("DHEAD_NEG90", ArcosPacket.commandInt(Arcos.DHEAD, -90));

        mine.put("VEL2_10_10", ArcosPacket.commandTwoBytes(Arcos.VEL2, 10, 10));
        mine.put("VEL2_NEG10_10", ArcosPacket.commandTwoBytes(Arcos.VEL2, -10, 10));
        mine.put("VEL2_10_NEG10", ArcosPacket.commandTwoBytes(Arcos.VEL2, 10, -10));
        mine.put("VEL2_127_NEG128", ArcosPacket.commandTwoBytes(Arcos.VEL2, 127, -128));
        mine.put("VEL2_0_0", ArcosPacket.commandTwoBytes(Arcos.VEL2, 0, 0));

        mine.put("SAY_BEEP", ArcosPacket.commandBytes(Arcos.SAY, new byte[] {5, 20}));
        mine.put("SAY_BEEP4", ArcosPacket.commandBytes(Arcos.SAY, new byte[] {5, 20, 5, 30}));

        for (Map.Entry<String, String> e : golden.entrySet()) {
            ArcosPacket p = mine.get(e.getKey());
            if (p == null) {
                fail(e.getKey(), "no Java case for this vector");
                continue;
            }
            check(e.getKey(), e.getValue(), p.toHex());
        }
        for (String k : mine.keySet()) {
            if (!golden.containsKey(k)) {
                fail(k, "Java case has no golden vector");
            }
        }
    }

    // ---------- codec round trip ----------

    private static void testRoundTrip() throws Exception {
        System.out.println();
        System.out.println("== round trip");

        ArcosPacket built = ArcosPacket.build(Arcos.SYNC_2);
        built.putStr("Pioneer");
        built.putStr("Pioneer");
        built.putStr("p3dx");
        byte[] frame = built.frame();

        ArcosPacket parsed = ArcosPacket.parse(frame, 0, frame.length);
        check("sync2 id", "2", String.valueOf(parsed.id()));
        check("sync2 name", "Pioneer", parsed.str());
        check("sync2 type", "Pioneer", parsed.str());
        check("sync2 subtype", "p3dx", parsed.str());

        // Signed 16-bit values must survive as two's complement in the payload.
        ArcosPacket ints = ArcosPacket.build(Arcos.SIP_STANDARD);
        ints.putI16(-1234);
        ints.putU16(50000);
        ints.putU8(200);
        byte[] f2 = ints.frame();
        ArcosPacket p2 = ArcosPacket.parse(f2, 0, f2.length);
        check("i16 round trip", "-1234", String.valueOf(p2.i16()));
        check("u16 round trip", "50000", String.valueOf(p2.u16()));
        check("u8 round trip", "200", String.valueOf(p2.u8()));
        check("payload exhausted", "0", String.valueOf(p2.remaining()));

        // An odd payload length exercises the checksum's trailing-byte XOR.
        ArcosPacket odd = ArcosPacket.build(0x42);
        odd.putU8(0xAB);
        byte[] f3 = odd.frame();
        ArcosPacket p3 = ArcosPacket.parse(f3, 0, f3.length);
        check("odd payload survives", "171", String.valueOf(p3.u8()));
    }

    private static void testChecksumRejection() {
        System.out.println();
        System.out.println("== corrupt frames are rejected");

        byte[] good = ArcosPacket.commandInt(Arcos.VEL, 300).frame();

        byte[] bad = good.clone();
        bad[5] ^= 0xFF;                       // flip a payload byte
        check("bad checksum rejected", "true", String.valueOf(rejects(bad)));

        byte[] badSync = good.clone();
        badSync[0] = 0x00;
        check("bad sync rejected", "true", String.valueOf(rejects(badSync)));

        byte[] badCount = good.clone();
        badCount[2] = 0x7F;                   // count disagrees with the real length
        check("bad count rejected", "true", String.valueOf(rejects(badCount)));

        check("good frame accepted", "false", String.valueOf(rejects(good)));
    }

    private static boolean rejects(byte[] frame) {
        try {
            ArcosPacket.parse(frame, 0, frame.length);
            return false;
        } catch (ArcosException e) {
            return true;
        }
    }

    // ---------- the stream framer ----------

    private static void testFramerResync() throws Exception {
        System.out.println();
        System.out.println("== framer");

        byte[] wanted = ArcosPacket.commandInt(Arcos.VEL, -300).frame();
        byte[] other = ArcosPacket.commandInt(Arcos.RVEL, 45).frame();

        // Line noise, then a header whose body was cut off, then a real frame. The
        // truncated frame must not swallow the good one that follows it.
        java.io.ByteArrayOutputStream s1 = new java.io.ByteArrayOutputStream();
        s1.write(new byte[] {0x11, (byte) 0xFA, 0x22, (byte) 0xFA, (byte) 0xFA, 0x33});
        s1.write(new byte[] {(byte) 0xFA, (byte) 0xFB, 0x06, 0x0B});
        s1.write(wanted);
        java.util.List<ArcosPacket> got = drain(s1.toByteArray());
        check("truncated frame does not eat the next", "1", String.valueOf(got.size()));
        if (got.size() == 1) {
            check("recovered payload", toHex(wanted), got.get(0).toHex());
        }

        // Two back-to-back frames in one read.
        java.io.ByteArrayOutputStream s2 = new java.io.ByteArrayOutputStream();
        s2.write(wanted);
        s2.write(other);
        got = drain(s2.toByteArray());
        check("two frames in one read", "2", String.valueOf(got.size()));

        // A frame split across every possible byte boundary still arrives exactly once.
        boolean allSplitsOk = true;
        for (int split = 1; split < wanted.length; split++) {
            PacketFramer f = new PacketFramer();
            f.append(wanted, 0, split);
            java.util.List<ArcosPacket> before = drainFrom(f);
            f.append(wanted, split, wanted.length - split);
            java.util.List<ArcosPacket> after = drainFrom(f);
            if (!before.isEmpty() || after.size() != 1
                    || !after.get(0).toHex().equals(toHex(wanted))) {
                allSplitsOk = false;
                System.out.println("          split at " + split + " failed");
            }
        }
        check("frame split at every boundary", "true", String.valueOf(allSplitsOk));

        // A byte-for-byte drip feed, the worst case for a slow serial line.
        PacketFramer drip = new PacketFramer();
        int count = 0;
        for (byte b : concat(wanted, other)) {
            drip.append(new byte[] {b}, 0, 1);
            while (drip.next() != null) {
                count++;
            }
        }
        check("byte-at-a-time delivery", "2", String.valueOf(count));

        // Garbage that happens to contain a plausible header must not wedge the framer.
        byte[] noise = new byte[512];
        for (int i = 0; i < noise.length; i++) {
            noise[i] = (byte) ((i * 37) & 0xFF);
        }
        java.io.ByteArrayOutputStream s3 = new java.io.ByteArrayOutputStream();
        s3.write(noise);
        s3.write(wanted);
        got = drain(s3.toByteArray());
        check("survives noise before a frame", "1", String.valueOf(got.size()));

        // More bytes than the buffer holds, with a good frame at the end.
        java.io.ByteArrayOutputStream s4 = new java.io.ByteArrayOutputStream();
        for (int i = 0; i < 12000; i++) {
            s4.write(0x5A);
        }
        s4.write(wanted);
        got = drain(s4.toByteArray());
        check("survives buffer overflow", "1", String.valueOf(got.size()));
    }

    private static java.util.List<ArcosPacket> drain(byte[] data) {
        PacketFramer f = new PacketFramer();
        f.append(data, 0, data.length);
        return drainFrom(f);
    }

    private static java.util.List<ArcosPacket> drainFrom(PacketFramer f) {
        java.util.List<ArcosPacket> out = new java.util.ArrayList<>();
        ArcosPacket p;
        while ((p = f.next()) != null) {
            out.add(p);
        }
        return out;
    }

    private static byte[] concat(byte[] a, byte[] b) {
        byte[] out = new byte[a.length + b.length];
        System.arraycopy(a, 0, out, 0, a.length);
        System.arraycopy(b, 0, out, a.length, b.length);
        return out;
    }

    // ---------- SIP decoding ----------

    private static void testSipDecode() throws Exception {
        System.out.println();
        System.out.println("== SIP decode");

        // Field order per ArRobot::processMotorPacket.
        ArcosPacket sip = ArcosPacket.build(Arcos.SIP_STANDARD);
        sip.putU16(2000);            // x, raw units
        sip.putU16(1000);            // y
        sip.putI16(1024);            // theta, 4096 units per full turn -> 90 degrees
        sip.putI16(300);             // left wheel mm/s
        sip.putI16(280);             // right wheel mm/s
        sip.putU8(124);              // battery, tenths of a volt -> 12.4 V
        sip.putU16(0x0000);          // stall / bumpers
        sip.putI16(1024);            // control heading setpoint
        sip.putU16(0x0021);          // flags: motors enabled (bit0) + estop (bit5)
        sip.putU8(0);                // compass
        sip.putU8(2);                // two sonar readings follow
        sip.putU8(3);
        sip.putU16(1500);
        sip.putU8(7);
        sip.putU16(800);
        byte[] frame = sip.frame();

        ArcosPacket parsed = ArcosPacket.parse(frame, 0, frame.length);
        ArcosRobot robot = new ArcosRobot(new NullTransport(), RobotParams.P3DX);
        RobotState s = robot.decodeSip(parsed);

        check("sip x mm", "970", String.valueOf(Math.round(s.x)));          // 2000 * 0.485
        check("sip y mm", "485", String.valueOf(Math.round(s.y)));          // 1000 * 0.485
        check("sip theta deg", "90", String.valueOf(Math.round(s.theta)));
        check("sip left vel", "300", String.valueOf(Math.round(s.leftVel)));
        check("sip right vel", "280", String.valueOf(Math.round(s.rightVel)));
        check("sip velocity", "290", String.valueOf(Math.round(s.velocity())));
        check("sip battery", "12.4", String.format("%.1f", s.batteryVoltage));
        check("sip motors enabled", "true", String.valueOf(s.motorsEnabled));
        check("sip estop", "true", String.valueOf(s.eStopPressed));
        check("sip sonar 3", "1500", String.valueOf(s.sonar[3]));
        check("sip sonar 7", "800", String.valueOf(s.sonar[7]));
        check("sip sonar 0 unknown", "-1", String.valueOf(s.sonar[0]));
        check("sip closest sonar", "800", String.valueOf(s.closestSonar()));
    }

    /** Stands in for a transport where the test only needs the decoding side. */
    private static final class NullTransport implements Transport {
        @Override public void open() { }
        @Override public int read(byte[] dst, int off, int len, int timeoutMs) { return 0; }
        @Override public void write(byte[] d) { }
        @Override public boolean isOpen() { return true; }
        @Override public String name() { return "null"; }
        @Override public void close() { }
    }

    // ---------- harness ----------

    private static void check(String label, String expected, String actual) {
        checks++;
        if (expected.equals(actual)) {
            System.out.println("  ok    " + label);
        } else {
            failures++;
            System.out.println("  FAIL  " + label);
            System.out.println("          expected: " + expected);
            System.out.println("          actual:   " + actual);
        }
    }

    private static void fail(String label, String why) {
        checks++;
        failures++;
        System.out.println("  FAIL  " + label + " - " + why);
    }

    private static String toHex(byte[] b) {
        StringBuilder sb = new StringBuilder();
        for (byte x : b) {
            if (sb.length() > 0) {
                sb.append(' ');
            }
            sb.append(String.format("%02X", x));
        }
        return sb.toString();
    }
}
